services:
  timescale:
    container_name: timescale
    image: timescale/timescaledb-ha:pg14-latest 
    restart: unless-stopped
    # volumes:
    #   - ./timescaledb-data:/home/postgres/pgdata/data 
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME} 
    ports:
      # remap this to 5433 when running timescale locally as 5432 is used by temporal pg.
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U weathercore" ]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - ouroboros-local
  weathercore:
    container_name: weathercore
    image: syahshiimi/ouroboros-weathercore:main
    user: 1001:1001
    restart: unless-stopped
    depends_on:
      weathercore-migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - ouroboros-local
  weathercore-migrations:
    container_name: weathercore-migrations
    image: syahshiimi/ouroboros-weathercore-migrations:main
    depends_on:
      timescale:
        condition: service_healthy
    user: 1001:1001
    env_file:
      - .env
    networks:
      - ouroboros-local

networks:
  ouroboros-local:
    driver: bridge
    name: ouroboros-local
