services:
  timescale:
    container_name: timescale
    image: timescale/timescaledb-ha:pg14-latest 
    restart: always 
    # volumes:
    #   - ./timescaledb-data:/home/postgres/pgdata/data 
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME} 
    ports:
      - 5433:5432
    networks:
      - ouroboros-local
  weathercore:
    container_name: weathercore
    image: syahshiimi/ouroboros-weathercore:main
    user: 1001:1001
    restart: always
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    networks:
      - ouroboros-local
  weathercore-migrations:
    container_name: weathercore-migrations
    image: syahshiimi/weatherchore-migration:latest
    user: 1001:1001
    env_file:
      - .env.docker
    networks:
      - ouroboros-local

networks:
  ouroboros-local:
    driver: bridge
    name: ouroboros-local
