version: '3.1'

services:
  db:
    image: timescale/timescaledb-ha:pg14-latest 
    restart: always 
    volumes:
      - ./timescaledb-data:/home/postgres/pgdata/data 
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME} 
    ports:
      - 5432:5432
