/* This file was generated by the generate-zod-schemas script */
/* DO NOT EDIT THIS FILE DIRECTLY. IT IS GENERATED FROM THE JSON SCHEMA FILES. */

import { z } from "zod"

export default z.object({ "metadata": z.object({ "stations": z.array(z.object({ "id": z.string(), "device_id": z.string(), "name": z.string(), "location": z.object({ "latitude": z.number(), "longitude": z.number() }) })), "reading_type": z.string(), "reading_unit": z.string() }), "items": z.array(z.object({ "timestamp": z.string(), "readings": z.array(z.object({ "station_id": z.string(), "value": z.number() })) })), "api_info": z.object({ "status": z.string() }) })
;