export const HumidityText = [
  "The air is thicker than the plot of a soap opera.",
  "Poseidon's breath lingers, even when he's on vacation.",
  "The humidity is so high, fish are evolving lungs.",
  "Singapore: Where your shirt becomes a mood ring.",
  "The air is hugging you. Constantly. Without consent.",
  "Legend says a dragon sneezed here once. It never dried.",
  "Humidity level: Merlion's permanent shower.",
  "The moisture spirits are feeling extra clingy today.",
  "It's not the heat, it's the... no, wait, it's both.",
  "Beware the invisible swamp that follows you everywhere.",
  "Today's forecast: Soupy with a chance of dampness.",
  "The air is so thick, you could cut it with a butter knife... if it hadn't melted.",
  "Humidity status: Your glasses fog up. Indoors.",
  "The moisture fairies are working overtime again.",
  "It's so humid, even the clouds are sweating.",
];
