export const rainfallText = [
  "Raindrops: the tears of clouds pondering their own existence.",
  "In the dry spell, even the concept of moisture becomes a distant memory.",
  "Each raindrop, a universe of possibilities crashing into our reality.",
  "The monsoon arrives, washing away certainties, leaving only questions in puddles.",
  "A single drop falls in the forest. Does it make a sound, or just a philosophical quandary?",
  "In the torrential downpour, we all become one with the cosmic soup.",
  "Humidity rises, blurring the lines between air, water, and existential dread.",
  "The sun peeks out, a brief reminder of the illusion we call 'dryness'.",
  "Rain falls equally on the just and unjust, but mostly on the unprepared.",
  "In the deluge, we find ourselves - soggy, confused, yet strangely liberated.",
  "Drought: when the sky hoards its wisdom, leaving us parched for meaning.",
  "Between droplets, we exist. In downpours, we transcend.",
  "The rain gauge measures water, but can it quantify the weight of wet socks?",
  "Precipitation probability: a percentage or a metaphor for life's uncertainties?",
  "In the rhythm of rain, we hear the universe's jazz improvisation.",
];
