services:
  feeder-worker:
    container_name: feeder-worker
    user: 1001:1001
    image: syahshiimi/ouroboros-feeder-worker:main
    env_file:
      - .env.docker
    networks:
      - ouroboros-local
  feeder-api:
    container_name: feeder-api
    user: 1001:1001
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${TEMPORAL_POSTGRES_USER}
      - POSTGRES_PWD=${TEMPORAL_POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgresql
    image: syahshiimi/ouroboros-feeder-api:main
    env_file:
      - .env.docker
    ports:
      - published: 4000
        target: 4000
    networks:
      - ouroboros-local

networks:
  ouroboros-local:
    driver: bridge
    name: ouroboros-local
