name: Feature-branch CI
 
on:
#  push:
#    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
      R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push @ouroboros/agents
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: apps/agents-merchants/Dockerfile
          push: true
          tags: syahshiimi/ouroboros-agents:featuretestingonly
          build-args: MARKET_PARTICIPANT=agents
