name: Main CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build and Test (Main)
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

  docker-build-agents-merchants:
    needs: build-and-test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: [agents, merchants]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract and transform branch name
        shell: bash
        run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          transformed_branch=$(echo "$branch" | sed 's/[^a-zA-Z0-9._-]/-/g')
          echo "branch=$transformed_branch" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build @ouroboros/${{ matrix.app}}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: apps/agents-merchants/Dockerfile
          push: true
          tags: syahshiimi/ouroboros-${{ matrix.app }}:${{ steps.extract_branch.outputs.branch }}
          build-args: MARKET_PARTICIPANT=${{ matrix.app }}

  docker-build-apps:
    needs: build-and-test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: [feeder, feeder-worker, weathercore]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract and transform branch name
        shell: bash
        run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          transformed_branch=$(echo "$branch" | sed 's/[^a-zA-Z0-9._-]/-/g')
          echo "branch=$transformed_branch" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build @ouroboros/${{ matrix.app}}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: syahshiimi/ouroboros-${{ matrix.app }}:${{ steps.extract_branch.outputs.branch }}
          build-args: MARKET_PARTICIPANT=${{ matrix.app }}